service: hello-world-offline

plugins:
  - serverless-webpack
  # - serverless-bundle
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-1
  stage: dev
  # profile: default
  # memorySize: 256 # optional, in MB, default is 1024

functions:
  hello:
    handler: handler.handler
    name: "${self:service}-${self:provider.stage}" # optional, Deployed Lambda name
    events:
      - http:
          path: /
          method: get
          cors: true

custom:
  serverless-offline:
    host: 0.0.0.0

  webpack:
    webpackConfig: ./webpack.local.js
    includeModules: false
    packager: "yarn"
